### ISSUE TITLE
Reverser challenge - I sorta broke it :(

### ISSUE THREAD

**Issue by galnicholas** [XxXOLEGXxX/Shenanigans-Tree-Rewritten#1]
Hullo, I kinda broke your game and I was really enjoying it :/ 

I'm up to 4 condensed chaos with transcend unlocked (currently have > 200,000 with all upgrades costing less than that bought. I think I went a bit overboard clicking the "predict unpredicted boredom" button. Now the reverser challenge is impossible to complete, but I also can't reset. So I'm stuck. Literally. I've left it running for hours but nothing happens. I've included my save file so you can take a look if you like.

`eyJ0YWIiOiJvcHRpb25zIiwidGltZSI6MTYyMDkwOTkzNDAxNSwiYXV0b3NhdmUiOnRydWUsIm5vdGlmeSI6e30sIm1zRGlzcGxheSI6ImFsd2F5cyIsIm9mZmxpbmVQcm9kIjp0cnVlLCJ2ZXJzaW9uVHlwZSI6Im9sZWdhdCIsInZlcnNpb24iOiIwLjM1LjAwMi0tIiwidGltZVBsYXllZCI6MTM4NjA2LjE5MzU0MDg1Mzg2LCJrZWVwR29pbmciOmZhbHNlLCJoYXNOYU4iOmZhbHNlLCJoaWRlQ2hhbGxlbmdlcyI6ZmFsc2UsInNob3dTdG9yeSI6dHJ1ZSwicG9pbnRzIjoiMjkyMy43NjMxNDcyNjMzMTYiLCJzdWJ0YWJzIjp7InMiOnsibWFpblRhYnMiOiJTaGVuYW5pZ2FucyJ9LCJhIjp7Im1haW5UYWJzIjoiQWNoaWV2ZW1lbnRzIn19LCJpbmZvYm94ZXMiOnt9LCJzIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIyOTI0MDY4NTA4MjEzMy40NjUiLCJ1cGdyYWRlVGltZSI6IjYwIiwiYmlnQnJhaW5Cb3JlZG9tIjoiMCIsImJpZ0JvaSI6IjEiLCJsZWwiOiIwIiwidXBncmFkZXMiOlsxMSwxMiwyMSwyMywzMSwzMiwyMiwxMywzMywzNCwxNF0sIm1pbGVzdG9uZXMiOltdLCJjaGFsbGVuZ2VzIjp7IjExIjoxLCIxMiI6MCwiMjEiOjB9LCJidXlhYmxlcyI6eyIxMSI6IjI2NTIiLCIxMiI6IjAiLCIyMSI6IjAiLCIzMSI6IjAiLCI0MSI6IjEiLCI1MSI6IjEiLCI2MSI6IjEiLCI3MSI6IjEifSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsImNsaWNrYWJsZXMiOnt9LCJhY3RpdmVDaGFsbGVuZ2UiOjEyLCJhY2hpZXZlbWVudHMiOltdfSwiYyI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiNCIsImJlc3QiOiI1IiwidG90YWwiOiIxMyIsImNoYW90aWNFbmVyZ3kiOiI1Njg5Ni4yODg0Mjg5MjgwNyIsImJ1eWFibGVzIjp7fSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6WzEyLDIxLDEzLDExLDMxLDIyXSwibWlsZXN0b25lcyI6WyIwIiwiMSIsIjIiLCIzIiwiNCJdLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiYWN0aXZlQ2hhbGxlbmdlIjpudWxsfSwidCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMjEyOTM3LjAwODY1MDIwNzciLCJidXlhYmxlcyI6e30sImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOlsxMSwyMiwyMSwzMywzMSwzMl0sIm1pbGVzdG9uZXMiOlsiMCIsIjEiLCIyIl0sImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9fSwiYWIiOnsidW5sb2NrZWQiOmZhbHNlLCJwb2ludHMiOiIwIiwiYnV5YWJsZXMiOnt9LCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9fSwiYSI6eyJ1bmxvY2tlZCI6dHJ1ZSwiYWNoaWV2ZW1lbnRzTG9sIjoiMCIsImJpbmdvUHVuZ28iOiIwIiwiYnV5YWJsZXMiOnt9LCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9LCJhY3RpdmVDaGFsbGVuZ2UiOm51bGx9LCJkaWZmIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIxIiwiYnV5YWJsZXMiOnt9LCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnsiMTEiOjAsIjEyIjowLCIyMSI6MCwiMjIiOjAsIjMxIjowfSwiYWN0aXZlQ2hhbGxlbmdlIjpudWxsfSwibiI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsInRvdGFsIjoiMCIsInllcyI6IjAiLCJidXlhYmxlcyI6e30sImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImFjdGl2ZUNoYWxsZW5nZSI6bnVsbH0sImsiOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJleHBlcmllbmNlcyI6IjAiLCJidXlhYmxlcyI6e30sImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sInllcyI6IjAifSwiaHFUcmVlIjp0cnVlfQ==`

**Comment by XxXOLEGXxX** [comment]
I'm sorry that it took about 24 days to respond (mostly because i literally forgot issue tab even existed), but have you ever tried to get more Warp of Nonsense (and if you did, then have you ever reset 3rd upgrade's effect?)

by the time you're gonna read this, you most likely have reached ng-- endgame
